pipeline {
    agent any

    stages {

        stage('Preparation') {
            steps {
                echo 'Preparing workspace...'
            }
        }

        stage('Build') {
            steps {
                echo 'Static HTML project - no build required'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Starting local server on http://localhost:8081'

                // Stops any previous server running on port 8081
                bat 'for /f "tokens=5" %a in (\'netstat -aon ^| find ":8081"\') do taskkill /F /PID %a'

                // Start server
                bat 'start cmd /c "cd app && python -m http.server 8081"'
            }
        }
    }

    post {
        success {
            echo 'Pipeline executed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
